// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceExplorer.Infrastructure.Data;

#nullable disable

namespace SpaceExplorer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_collections_user_id");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiDescription")
                        .HasColumnType("text")
                        .HasColumnName("ai_description");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EarthDate")
                        .HasColumnType("date")
                        .HasColumnName("earth_date");

                    b.Property<string>("NasaImageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nasa_image_id");

                    b.Property<string>("NasaImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nasa_image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collection_items");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_collection_items_collection_id");

                    b.ToTable("collection_items", (string)null);
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.CollectionItemTag", b =>
                {
                    b.Property<Guid>("CollectionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_item_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("CollectionItemId", "TagId")
                        .HasName("pk_collection_item_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_collection_item_tags_tag_id");

                    b.ToTable("collection_item_tags", (string)null);
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_user_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Collection", b =>
                {
                    b.HasOne("SpaceExplorer.Domain.Entities.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collections_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.CollectionItem", b =>
                {
                    b.HasOne("SpaceExplorer.Domain.Entities.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_items_collections_collection_id");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.CollectionItemTag", b =>
                {
                    b.HasOne("SpaceExplorer.Domain.Entities.CollectionItem", "CollectionItem")
                        .WithMany("CollectionItemTags")
                        .HasForeignKey("CollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_item_tags_collection_items_collection_item_id");

                    b.HasOne("SpaceExplorer.Domain.Entities.Tag", "Tag")
                        .WithMany("CollectionItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_item_tags_tags_tag_id");

                    b.Navigation("CollectionItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Tag", b =>
                {
                    b.HasOne("SpaceExplorer.Domain.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.CollectionItem", b =>
                {
                    b.Navigation("CollectionItemTags");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.Tag", b =>
                {
                    b.Navigation("CollectionItemTags");
                });

            modelBuilder.Entity("SpaceExplorer.Domain.Entities.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
